@Squares.Api_HostAddress = http://localhost:5272

GET {{Squares.Api_HostAddress}}/api/squares/
Accept: application/json

###

POST {{Squares.Api_HostAddress}}/api/squares/
Accept: application/json

###

DELETE {{Squares.Api_HostAddress}}/api/squares/
Accept: application/json